# Generated by Django 2.2.9 on 2020-01-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='origem',
            field=models.CharField(choices=[('Paypal', 'paypal'), ('Caixa', 'caixa'), ('Mercado pago', 'mercado_pago')], max_length=20),
        ),
    ]
