# Generated by Django 2.2.6 on 2020-01-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quem', models.CharField(max_length=30)),
                ('origem', models.CharField(choices=[('Paypal', 'paypal'), ('Caixa', 'caixa'), ('Mercado pago', 'mercado pago')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
