# Generated by Django 2.2.6 on 2020-01-14 22:09

from django.db import migrations, models
import extrator.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('paypal_document', models.FileField(upload_to=extrator.utils.PathRename('media/docs/'))),
                ('mp_document', models.FileField(upload_to=extrator.utils.PathRename('media/docs/'))),
                ('cef_document', models.FileField(upload_to=extrator.utils.PathRename('media/docs/'))),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
