# Generated by Django 2.2.8 on 2020-01-15 16:30

from django.db import migrations, models
import extrator.utils


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cef_document',
            field=models.FileField(upload_to=extrator.utils.PathRename('docs/')),
        ),
        migrations.AlterField(
            model_name='document',
            name='mp_document',
            field=models.FileField(upload_to=extrator.utils.PathRename('docs/')),
        ),
        migrations.AlterField(
            model_name='document',
            name='paypal_document',
            field=models.FileField(upload_to=extrator.utils.PathRename('docs/')),
        ),
    ]
